2021-10-23 11:08:04 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 0 and 3
2021-10-23 11:08:04 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 1 and 4
2021-10-23 11:08:04 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 3 and 6
2021-10-23 11:08:04 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 4 and 7
2021-10-23 11:08:04 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 6 and 9
2021-10-23 11:08:04 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 7 and 10
2021-10-23 11:08:06 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:06 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:06 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:06 ERROR (SyncWorker_2) [homeassistant.loader] The custom integration 'nodered' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
2021-10-23 11:08:06 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration lovelace_gen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:06 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration clean_up_snapshots_service which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:06 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration weatherbit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:06 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration presence_simulation which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:06 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:06 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:06 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:06 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:06 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration myenergi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:06 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration media_player_template which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:07 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:07 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration temperature_feels_like which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:07 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration myq which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:07 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration mail_and_packages which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:07 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:07 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-23 11:08:26 WARNING (MainThread) [homeassistant.config] Invalid internal_url set. It's not allowed to have a path (/bla)
2021-10-23 11:08:26 WARNING (MainThread) [homeassistant.config] Invalid external_url set. It's not allowed to have a path (/bla)
2021-10-23 11:08:32 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=73 from 2021-10-23 13:23:07)
2021-10-23 11:08:37 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f217959c0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-10-23 11:08:54 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2021-10-23 11:08:54 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2021-10-23 11:08:54 WARNING (MainThread) [homeassistant.components.weather] Setup of weather platform pirateweather is taking over 10 seconds.
2021-10-23 11:08:56 WARNING (MainThread) [homeassistant.config_entries] Config entry 'benchdog93@gmail.com' for uptimerobot integration not ready yet: Request timeout for 'https://api.uptimerobot.com/v2/getMonitors'; Retrying in background
2021-10-23 11:08:56 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Home' for accuweather integration not ready yet; Retrying in background
2021-10-23 11:08:56 WARNING (MainThread) [homeassistant.components.alarm_control_panel] Setup of alarm_control_panel platform manual is taking over 10 seconds.
2021-10-23 11:08:56 WARNING (MainThread) [homeassistant.setup] Setup of webostv is taking over 10 seconds.
2021-10-23 11:08:56 WARNING (MainThread) [homeassistant.components.weather] Setup of weather platform openweathermap is taking over 10 seconds.
2021-10-23 11:08:56 WARNING (SyncWorker_5) [homeassistant.components.local_file.camera] Could not read camera mail_usps image from file: /custom_components/mail_and_packages/mail_none.gif
2021-10-23 11:08:56 WARNING (MainThread) [alexapy.alexalogin] No access token found; falling back to credential login instead of oauth.
2021-10-23 11:08:59 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 34cf86c0b787150663ccd67f1f4949b1e2c916a1eaeb0bb6c3fe85a823a891f6 from 192.168.1.1
2021-10-23 11:09:01 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 34cf86c0b787150663ccd67f1f4949b1e2c916a1eaeb0bb6c3fe85a823a891f6 from 192.168.1.1
2021-10-23 11:09:05 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 18c5cb337b92361e3c2bedca7a9415625191a874607fa635050bccb53054adbe from 192.168.1.1
2021-10-23 11:09:08 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 34cf86c0b787150663ccd67f1f4949b1e2c916a1eaeb0bb6c3fe85a823a891f6 from 192.168.1.1
2021-10-23 11:09:13 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform pirateweather is taking over 10 seconds.
2021-10-23 11:09:13 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform command_line is taking over 10 seconds.
2021-10-23 11:09:13 WARNING (MainThread) [homeassistant.components.esphome] Can't connect to ESPHome API for nook-light (192.168.1.124): Error connecting to ('192.168.1.124', 6053): [Errno 113] Connect call failed ('192.168.1.124', 6053)
2021-10-23 11:09:13 WARNING (MainThread) [homeassistant.components.esphome] Can't connect to ESPHome API for shelly-vintage-1 (192.168.1.115): Error connecting to ('192.168.1.115', 6053): [Errno 113] Connect call failed ('192.168.1.115', 6053)
2021-10-23 11:09:13 WARNING (MainThread) [homeassistant.components.esphome] Can't connect to ESPHome API for washer-dryer (192.168.1.132): Error connecting to ('192.168.1.132', 6053): [Errno 113] Connect call failed ('192.168.1.132', 6053)
2021-10-23 11:09:23 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 34cf86c0b787150663ccd67f1f4949b1e2c916a1eaeb0bb6c3fe85a823a891f6 from 192.168.1.1
2021-10-23 11:09:28 WARNING (MainThread) [zigpy_znp.zigbee.application] Your network is using the insecure Zigbee2MQTT network key!
2021-10-23 11:09:29 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ (states('sensor.benchdog93_home_assistant_config_last_build_duration') | float / 60) | round(2) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-23 11:09:29 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ (states('sensor.benchdog93_home_assistant_config_last_build_duration') | float / 60) | round(2) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-23 11:09:30 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 154, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-10-23 11:09:30 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 368, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-10-23 11:09:30 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-10-23 11:09:30 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 85, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-10-23 11:09:34 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.cabinet_lights_consumption (kWh) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2021-10-23 11:09:34 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.desktop_circuit_consumption (kWh) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2021-10-23 11:09:34 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.ewva_circuit_consumption (kWh) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2021-10-23 11:09:34 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.sink_light_consumption (kWh) does not match the unit of already compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None
2021-10-23 11:09:36 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.desktop_daily_energy has unknown unit W
2021-10-23 11:09:36 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.ewva_daily_energy has unknown unit W
2021-10-23 11:09:36 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.sink_light_daily_energy has unknown unit W
2021-10-23 11:09:36 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.cabinet_lights_daily_energy has unknown unit W
2021-10-23 11:09:36 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.master_bath_light_daily_energy has unknown unit W
2021-10-23 11:09:36 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.master_bath_fan_daily_energy has unknown unit W
2021-10-23 11:09:37 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.pond_aerator_daily_energy has unknown unit kW
2021-10-23 11:09:54 WARNING (MainThread) [homeassistant.components.camera] Setup of camera platform synology_dsm is taking over 10 seconds.
2021-10-23 11:09:54 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform synology_dsm is taking over 10 seconds.
2021-10-23 11:10:02 WARNING (MainThread) [homeassistant.components.media_player] Updating webostv media_player took longer than the scheduled update interval 0:00:10
2021-10-23 11:10:07 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.livingroom_tv is taking over 10 seconds
2021-10-23 11:10:07 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.mancave_tv is taking over 10 seconds
2021-10-23 11:10:10 ERROR (MainThread) [homeassistant.components.uptimerobot] Error fetching uptimerobot data: Request timeout for 'https://api.uptimerobot.com/v2/getMonitors'
2021-10-23 11:10:15 WARNING (MainThread) [homeassistant.components.media_player] Updating webostv media_player took longer than the scheduled update interval 0:00:10
2021-10-23 11:10:21 ERROR (MainThread) [homeassistant.components.upnp] Error requesting Netgear R6400 v2:EWVisualArts data: [Errno None] Can not write request body for http://192.168.1.1:1780/control?WANCommonInterfaceConfig
2021-10-23 11:27:07 WARNING (MainThread) [zeroconf] Received invalid packet from ('192.168.1.62', 5353) at offset 106 while unpacking b'\x00\x00\x84\x00\x00\x00\x00\x04\x00\x00\x00\x01\x00\x00\x0c\x00\x01\x00\x00\x01,\x00\x04\x02\x880\x00\x02\x880\x00\x00!\x80\x01\x00\x00\x01,\x00\x0b\xf3\x08\x80\xef\xf3\t\x03\x81rF\x00\x07MyQ-1EB\x05local\x00\x00\x01\x80\x01\x00\x00\x01,\x00\x04\xc0\xa8\x01>\x02\x880\x00\x00/\x80\x01\x00\x00\x01,\x00\x0b\x02\x880\x00\x00\x05\x00\x08\x00\x00@'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol/incoming.py", line 111, in _parse_data
    parser_call()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol/incoming.py", line 105, in _initial_parse
    self.read_others()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol/incoming.py", line 185, in read_others
    domain = self.read_name()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol/incoming.py", line 275, in read_name
    self.offset = self._decode_labels_at_offset(self.offset, labels, seen_pointers)
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_protocol/incoming.py", line 315, in _decode_labels_at_offset
    raise IncomingDecodeError("Corrupt packet received while decoding name")
zeroconf._exceptions.IncomingDecodeError: Corrupt packet received while decoding name
2021-10-23 12:10:11 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.washing_machine_daily_energy has unknown unit kW
2021-10-23 12:10:11 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.cloths_dryer_daily_energy has unknown unit kW
2021-10-23 12:16:28 ERROR (MainThread) [homeassistant.components.uptimerobot] Error fetching uptimerobot data: Request exception for 'https://api.uptimerobot.com/v2/getMonitors' with - [Errno 104] Connection reset by peer
2021-10-23 13:16:43 WARNING (SyncWorker_2) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 0 and 3
2021-10-23 13:16:43 WARNING (SyncWorker_2) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 1 and 4
2021-10-23 13:16:43 WARNING (SyncWorker_2) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 3 and 6
2021-10-23 13:16:43 WARNING (SyncWorker_2) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 4 and 7
2021-10-23 13:16:43 WARNING (SyncWorker_2) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 6 and 9
2021-10-23 13:16:43 WARNING (SyncWorker_2) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 7 and 10
2021-10-23 13:16:44 WARNING (MainThread) [homeassistant.config] Invalid internal_url set. It's not allowed to have a path (/bla)
2021-10-23 13:16:44 WARNING (MainThread) [homeassistant.config] Invalid external_url set. It's not allowed to have a path (/bla)
2021-10-23 13:17:21 WARNING (SyncWorker_15) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 0 and 3
2021-10-23 13:17:21 WARNING (SyncWorker_15) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 1 and 4
2021-10-23 13:17:21 WARNING (SyncWorker_15) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 3 and 6
2021-10-23 13:17:21 WARNING (SyncWorker_15) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 4 and 7
2021-10-23 13:17:21 WARNING (SyncWorker_15) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 6 and 9
2021-10-23 13:17:21 WARNING (SyncWorker_15) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 7 and 10
2021-10-23 13:17:22 WARNING (MainThread) [homeassistant.config] Invalid internal_url set. It's not allowed to have a path (/bla)
2021-10-23 13:17:22 WARNING (MainThread) [homeassistant.config] Invalid external_url set. It's not allowed to have a path (/bla)
2021-10-23 13:17:30 WARNING (SyncWorker_9) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 0 and 3
2021-10-23 13:17:30 WARNING (SyncWorker_9) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 1 and 4
2021-10-23 13:17:30 WARNING (SyncWorker_9) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 3 and 6
2021-10-23 13:17:30 WARNING (SyncWorker_9) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 4 and 7
2021-10-23 13:17:30 WARNING (SyncWorker_9) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 6 and 9
2021-10-23 13:17:30 WARNING (SyncWorker_9) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 7 and 10
2021-10-23 13:17:31 WARNING (MainThread) [homeassistant.config] Invalid internal_url set. It's not allowed to have a path (/bla)
2021-10-23 13:17:31 WARNING (MainThread) [homeassistant.config] Invalid external_url set. It's not allowed to have a path (/bla)
2021-10-23 13:23:53 WARNING (SyncWorker_6) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 0 and 4
2021-10-23 13:23:53 WARNING (SyncWorker_6) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 1 and 5
2021-10-23 13:23:53 WARNING (SyncWorker_6) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "name". Check lines 2 and 6
2021-10-23 13:23:53 WARNING (SyncWorker_6) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 4 and 8
2021-10-23 13:23:53 WARNING (SyncWorker_6) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 5 and 9
2021-10-23 13:23:53 WARNING (SyncWorker_6) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "name". Check lines 6 and 10
2021-10-23 13:23:53 WARNING (SyncWorker_6) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 8 and 12
2021-10-23 13:23:53 WARNING (SyncWorker_6) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 9 and 13
2021-10-23 13:23:53 WARNING (SyncWorker_6) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "name". Check lines 10 and 14
2021-10-23 13:23:54 WARNING (MainThread) [homeassistant.config] Invalid internal_url set. It's not allowed to have a path (/bla)
2021-10-23 13:23:54 WARNING (MainThread) [homeassistant.config] Invalid external_url set. It's not allowed to have a path (/bla)
2021-10-23 13:30:41 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 0 and 4
2021-10-23 13:30:41 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 1 and 5
2021-10-23 13:30:41 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "name". Check lines 2 and 6
2021-10-23 13:30:41 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 4 and 8
2021-10-23 13:30:41 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 5 and 9
2021-10-23 13:30:41 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "name". Check lines 6 and 10
2021-10-23 13:30:41 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 8 and 12
2021-10-23 13:30:41 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 9 and 13
2021-10-23 13:30:41 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "name". Check lines 10 and 14
2021-10-23 13:30:44 WARNING (MainThread) [homeassistant.config] Invalid external_url set. It's not allowed to have a path (/bla)
2021-10-23 13:40:29 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139781550040784] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds
2021-10-23 15:35:58 WARNING (SyncWorker_25) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 0 and 4
2021-10-23 15:35:58 WARNING (SyncWorker_25) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 1 and 5
2021-10-23 15:35:58 WARNING (SyncWorker_25) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "name". Check lines 2 and 6
2021-10-23 15:35:58 WARNING (SyncWorker_25) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 4 and 8
2021-10-23 15:35:58 WARNING (SyncWorker_25) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 5 and 9
2021-10-23 15:35:58 WARNING (SyncWorker_25) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "name". Check lines 6 and 10
2021-10-23 15:35:58 WARNING (SyncWorker_25) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 8 and 12
2021-10-23 15:35:58 WARNING (SyncWorker_25) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 9 and 13
2021-10-23 15:35:58 WARNING (SyncWorker_25) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "name". Check lines 10 and 14
2021-10-23 15:35:59 WARNING (MainThread) [homeassistant.config] Invalid external_url set. It's not allowed to have a path (/bla)
2021-10-23 15:36:04 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 0 and 4
2021-10-23 15:36:04 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 1 and 5
2021-10-23 15:36:04 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "name". Check lines 2 and 6
2021-10-23 15:36:04 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 4 and 8
2021-10-23 15:36:04 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 5 and 9
2021-10-23 15:36:04 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "name". Check lines 6 and 10
2021-10-23 15:36:04 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "platform". Check lines 8 and 12
2021-10-23 15:36:04 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "entity_id". Check lines 9 and 13
2021-10-23 15:36:04 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/sensors/statistics_energy.yaml contains duplicate key "name". Check lines 10 and 14
2021-10-23 15:36:05 WARNING (MainThread) [homeassistant.config] Invalid external_url set. It's not allowed to have a path (/bla)
2021-10-23 15:36:10 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /homeassistant/restart request Server disconnected
